library(functional)
initial <- read.table("household_power_consumption_subset.txt", header = TRUE, sep=";")
png(filename = "plot3.png", width = 480, height = 480, units = "px", bg="transparent")
x <- as.POSIXct(paste(initial$Date, initial$Time), format="%d/%m/%Y %H:%M:%S")
selectors <- Filter(Curry(grepl, "^Sub_metering"), colnames(initial))
colors <- c("black","red","blue")
matplot(x, initial[selectors], type="lll", lty = 1, lwd=1, col=colors,
        ylab="Energy sub metering", xlab="", xaxt="n")
axis.POSIXct(1,x, format="%a")
legend("topright", lwd=1, col = colors, legend = selectors)
dev.off()
